export const CHANGE_STORE_VIEW = 'Tracki/CHANGE_STORE_VIEW';

export const TAB_KEYS = ['store', 'saved', 'coupons', 'orders'];

export const FETCH_DATA_PRODUCTS_REQUESTED =
  'Tracki/FETCH_DATA_PRODUCTS_REQUESTED';
export const FETCH_DATA_PRODUCTS_SUCCEED = 'Tracki/FETCH_DATA_PRODUCTS_SUCCEED';
export const FETCH_DATA_PRODUCTS_FAILED = 'Tracki/FETCH_DATA_PRODUCTS_FAILED';

export const FETCH_DATA_COUPONS_REQUESTED =
  'Tracki/FETCH_DATA_COUPONS_REQUESTED';
export const FETCH_DATA_COUPONS_SUCCEED = 'Tracki/FETCH_DATA_COUPONS_SUCCEED';
export const FETCH_DATA_COUPONS_FAILED = 'Tracki/FETCH_DATA_COUPONS_FAILED';
