export const GET_LIST_CONTACT_REQUESTED = 'Tracki/GET_LIST_CONTACT_REQUESTED';
export const GET_LIST_CONTACT_SUCCESSED = 'Tracki/GET_LIST_CONTACT_SUCCESSED';
export const GET_LIST_CONTACT_FAILED = 'Tracki/GET_LIST_CONTACT_FAILED';

export const UPDATE_LIST_CONTACT_REQUESTED =
  'Tracki/UPDATE_LIST_CONTACT_REQUESTED';
export const UPDATE_LIST_CONTACT_SUCCESSED =
  'Tracki/UPDATE_LIST_CONTACT_SUCCESSED';
export const UPDATE_LIST_CONTACT_FAILED = 'Tracki/UPDATE_LIST_CONTACT_FAILED';

export const CREATE_NEW_CONTACT_REQUESTED =
  'Tracki/CREATE_NEW_CONTACT_REQUESTED';
export const CREATE_NEW_CONTACT_SUCCESSED =
  'Tracki/CREATE_NEW_CONTACT_SUCCESSED';
export const CREATE_NEW_CONTACT_FAILED = 'Tracki/CREATE_NEW_CONTACT_FAILED';

export const SEARCH_CONTACT_REQUESTED = 'Tracki/SEARCH_CONTACT_REQUESTED';
export const SEARCH_CONTACT_SUCCEED = 'Tracki/SEARCH_CONTACT_SUCCEED';
export const SEARCH_CONTACT_FAILED = 'Tracki/SEARCH_CONTACT_FAILED';

export const EDIT_CONTACT_REQUESTED = 'Tracki/EDIT_CONTACT_REQUESTED';
export const EDIT_CONTACT_SUCCEED = 'Tracki/EDIT_CONTACT_SUCCEED';
export const EDIT_CONTACT_FAILED = 'Tracki/EDIT_CONTACT_FAILED';

export const DELETE_CONTACT_REQUESTED = 'Tracki/DELETE_CONTACT_REQUESTED';
export const DELETE_CONTACT_SUCCEED = 'Tracki/DELETE_CONTACT_SUCCEED';
export const DELETE_CONTACT_FAILED = 'Tracki/DELETE_CONTACT_FAILED';
