export const CHECK_DEVICEID_ASSIGNED_REQUESTED =
  'Tracki/CHECK_DEVICEID_ASSIGNED_REQUESTED';
export const CHECK_DEVICEID_ASSIGNED_SUCCESSED =
  'Tracki/CHECK_DEVICEID_ASSIGNED_SUCCESSED';
export const CHECK_DEVICEID_ASSIGNED_FAILED =
  'Tracki/CHECK_DEVICEID_ASSIGNED_FAILED';
export const GET_DEVICE_PLAN_REQUESTED = 'Tracki/GET_DEVICE_PLAN_REQUESTED';
export const GET_DEVICE_PLAN_SUCCESSED = 'Tracki/GET_DEVICE_PLAN_SUCCESSED';
export const GET_DEVICE_PLAN_FAILED = 'Tracki/GET_DEVICE_PLAN_FAILED';
export const UPDATE_STORE = 'Tracki/UPDATE_STORE';
export const GET_TOKEN_FOR_PAYMENT_REQUESTED =
  'Tracki/GET_TOKEN_FOR_PAYMENT_REQUESTED';
export const GET_TOKEN_FOR_PAYMENT_SUCCESSED =
  'Tracki/GET_TOKEN_FOR_PAYMENT_SUCCESSED';
export const GET_TOKEN_FOR_PAYMENT_FAILED =
  'Tracki/GET_TOKEN_FOR_PAYMENT_FAILED';
