export const GET_DEVICE_BY_TOKEN_REQUESTED =
  'Tracki/GET_DEVICE_BY_TOKEN_REQUESTED';
export const GET_DEVICE_BY_TOKEN_SUCCESSED =
  'Tracki/GET_DEVICE_BY_TOKEN_SUCCESSED';
export const GET_DEVICE_BY_TOKEN_FAILED = 'Tracki/GET_DEVICE_BY_TOKEN_FAILED';
