export const MAP_ACTIONS = {
  CREATE_RECTANGLE: 'CREATE_RECTANGLE',
  CREATE_POLYGON: 'CREATE_POLYGON',
  CREATE_CIRCLE: 'CREATE_CIRCLE',
  DEFAULT: 'DEFAULT',
};

export const LEAFLET_PADDING_OPTIONS = {
  paddingTopLeft: [440, 0],
  paddingBottomRight: [100, 0],
};
