export const GET_TRACKERS_REQUESTED = 'Tracki/GET_TRACKERS_REQUESTED';
export const GET_TRACKERS_SUCCEED = 'Tracki/GET_TRACKERS_SUCCEED';
export const GET_TRACKERS_FAILED = 'Tracki/GET_TRACKERS_FAILED';

export const SEARCH_TRACKERS_REQUESTED = 'Tracki/SEARCH_TRACKERS_REQUESTED';
export const SEARCH_TRACKERS_SUCCEED = 'Tracki/SEARCH_TRACKERS_SUCCEED';
export const SEARCH_TRACKERS_FAILED = 'Tracki/SEARCH_TRACKERS_FAILED';

export const SEARCH_GEOFENCES_REQUESTED = 'Tracki/SEARCH_GEOFENCES_REQUESTED';
export const SEARCH_GEOFENCES_SUCCEED = 'Tracki/SEARCH_GEOFENCES_SUCCEED';
export const SEARCH_GEOFENCES_FAILED = 'Tracki/SEARCH_GEOFENCES_FAILED';

export const SELECTED_TRACKER = 'Tracki/SELECTED_TRACKER';
export const RESET_SELECTED_TRACKER = 'Tracki/RESET_SELECTED_TRACKER';

export const SELECTED_GEOFENCE = 'Tracki/SELECTED_GEOFENCE';
export const RESET_SELECTED_GEOFENCE = 'Tracki/RESET_SELECTED_GEOFENCE';

export const GET_GEOFENCES_REQUESTED = 'Tracki/GET_GEOFENCES_REQUESTED';
export const GET_GEOFENCES_SUCCEED = 'Tracki/GET_GEOFENCES_SUCCEED';
export const GET_GEOFENCES_FAILED = 'Tracki/GET_GEOFENCES_FAILED';

export const UPDATE_GEOFENCE_REQUESTED = 'Tracki/UPDATE_GEOFENCE_REQUESTED';
export const UPDATE_GEOFENCE_SUCCEED = 'Tracki/UPDATE_GEOFENCE_SUCCEED';
export const UPDATE_GEOFENCE_FAILED = 'Tracki/UPDATE_GEOFENCE_FAILED';
