export const GET_TRACKERS_REQUESTED = 'Tracki/GET_TRACKERS_REQUESTED';
export const GET_TRACKERS_SUCCEED = 'Tracki/GET_TRACKERS_SUCCEED';
export const GET_TRACKERS_FAILED = 'Tracki/GET_TRACKERS_FAILED';

export const SEARCH_TRACKERS_REQUESTED = 'Tracki/SEARCH_TRACKERS_REQUESTED';
export const SEARCH_TRACKERS_SUCCEED = 'Tracki/SEARCH_TRACKERS_SUCCEED';
export const SEARCH_TRACKERS_FAILED = 'Tracki/SEARCH_TRACKERS_FAILED';

export const SEARCH_GEOFENCES_REQUESTED = 'Tracki/SEARCH_GEOFENCES_REQUESTED';
export const SEARCH_GEOFENCES_SUCCEED = 'Tracki/SEARCH_GEOFENCES_SUCCEED';
export const SEARCH_GEOFENCES_FAILED = 'Tracki/SEARCH_GEOFENCES_FAILED';

export const SELECTED_TRACKER = 'Tracki/SELECTED_TRACKER';
export const RESET_SELECTED_TRACKER = 'Tracki/RESET_SELECTED_TRACKER';
export const RESET_NEW_GEOFENCE = 'Tracki/RESET_NEW_GEOFENCE';
export const SELECTED_GEOFENCE = 'Tracki/SELECTED_GEOFENCE';
export const RESET_SELECTED_GEOFENCE = 'Tracki/RESET_SELECTED_GEOFENCE';

export const GET_GEOFENCES_REQUESTED = 'Tracki/GET_GEOFENCES_REQUESTED';
export const GET_GEOFENCES_SUCCEED = 'Tracki/GET_GEOFENCES_SUCCEED';
export const GET_GEOFENCES_FAILED = 'Tracki/GET_GEOFENCES_FAILED';

export const SAVE_GEOFENCE_REQUESTED = 'Tracki/SAVE_GEOFENCE_REQUESTED';
export const SAVE_GEOFENCE_SUCCEED = 'Tracki/SAVE_GEOFENCE_SUCCEED';
export const SAVE_GEOFENCE_FAILED = 'Tracki/SAVE_GEOFENCE_FAILED';

export const CREATE_GEOFENCE_REQUESTED = 'Tracki/CREATE_GEOFENCE_REQUESTED';
export const CREATE_GEOFENCE_SUCCEED = 'Tracki/CREATE_GEOFENCE_SUCCEED';
export const CREATE_GEOFENCE_FAILED = 'Tracki/CREATE_GEOFENCE_FAILED';

export const REMOVE_GEOFENCE_REQUESTED = 'Tracki/REMOVE_GEOFENCE_REQUESTED';
export const REMOVE_GEOFENCE_SUCCEED = 'Tracki/REMOVE_GEOFENCE_SUCCEED';
export const REMOVE_GEOFENCE_FAILED = 'Tracki/REMOVE_GEOFENCE_FAILED';

export const UNLINK_TRACKERS_REQUESTED = 'Tracki/UNLINK_TRACKERS_REQUESTED';
export const UNLINK_TRACKERS_SUCCEED = 'Tracki/UNLINK_TRACKERS_SUCCEED';
export const UNLINK_TRACKERS_FAILED = 'Tracki/UNLINK_TRACKERS_FAILED';

export const LINK_TRACKERS_REQUESTED = 'Tracki/LINK_TRACKERS_REQUESTED';
export const LINK_TRACKERS_SUCCEED = 'Tracki/LINK_TRACKERS_SUCCEED';
export const LINK_TRACKERS_FAILED = 'Tracki/LINK_TRACKERS_FAILED';

export const UPDATE_TRACKERS_UNLINK_GEOFENCE =
  'Tracki/UPDATE_TRACKERS_UNLINK_GEOFENCE';
export const UPDATE_TRACKERS_LINKED_GEOFENCE =
  'Tracki/UPDATE_TRACKERS_LINKED_GEOFENCE';

export const EDIT_GEOFENCE = 'Tracki/EDIT_GEOFENCE';
export const CREATE_NEW_GEOFENCE = 'Tracki/CREATE_NEW_GEOFENCE';
export const UPDATE_NEW_GEOFENCE = 'Tracki/UPDATE_NEW_GEOFENCE';
export const UPDATE_GEOFENCE = 'Tracki/UPDATE_GEOFENCE';
export const UPDATE_TRACKER = 'Tracki/UPDATE_TRACKER';

export const REFRESH_LOACTION_REQUESTED = 'Tracki/REFRESH_LOACTION_REQUESTED';

export const GET_SMS_COUNTER_REQUESTED = 'Tracki/GET_SMS_COUNTER_REQUESTED';
export const GET_SMS_COUNTER_SUCCEED = 'Tracki/GET_SMS_COUNTER_SUCCEED';
export const GET_SMS_COUNTER_FAILED = 'Tracki/GET_SMS_COUNTER_FAILED';

export const GET_DEVICE_SUBSCRIPTION_REQUESTED =
  'Tracki/GET_DEVICE_SUBSCRIPTION_REQUESTED';
export const GET_DEVICE_SUBSCRIPTION_SUCCEED =
  'Tracki/GET_DEVICE_SUBSCRIPTION_SUCCEED';
export const GET_DEVICE_SUBSCRIPTION_FAILED =
  'Tracki/GET_DEVICE_SUBSCRIPTION_FAILED';

export const GET_SOS_ALERT_TRACKER_REQUESTED =
  'Tracki/GET_SOS_ALERT_TRACKER_REQUESTED';
export const GET_SOS_ALERT_TRACKER_SUCCEED =
  'Tracki/GET_SOS_ALERT_TRACKER_SUCCEED';
export const GET_SOS_ALERT_TRACKER_FAILED =
  'Tracki/GET_SOS_ALERT_TRACKER_FAILED';
