export const GET_PROFILE_REQUESTED = 'Tracki/App/GET_PROFILE_REQUESTED';
export const GET_PROFILE_SUCCEED = 'Tracki/App/GET_PROFILE_SUCCEED';
export const GET_PROFILE_FAILED = 'Tracki/App/GET_PROFILE_FAILED';

export const PAGE_LOADING_PROGRESS_CHANGE =
  'Tracki/App/PAGE_LOADING_PROGRESS_CHANGE';
