export const UPDATE_PASSWORD_REQUESTED =
  'Tracki/Auth/UPDATE_PASSWORD_REQUESTED';
export const UPDATE_PASSWORD_SUCCEED = 'Tracki/Auth/UPDATE_PASSWORD_SUCCEED';
export const UPDATE_PASSWORD_FAILED = 'Tracki/Auth/UPDATE_PASSWORD_FAILED';
