export const GET_TRACKERS_REQUESTED = 'Tracki/App/GET_TRACKERS_REQUESTED';
export const GET_TRACKERS_SUCCEED = 'Tracki/App/GET_TRACKERS_SUCCEED';
export const GET_TRACKERS_FAILED = 'Tracki/App/GET_TRACKERS_FAILED';
export const GET_PROFILE_REQUESTED = 'Tracki/App/GET_PROFILE_REQUESTED';
export const GET_PROFILE_SUCCEED = 'Tracki/App/GET_PROFILE_SUCCEED';
export const GET_PROFILE_FAILED = 'Tracki/App/GET_PROFILE_FAILED';
export const LOGOUT_REQUESTED = 'Tracki/App/LOGOUT_REQUESTED';
export const LOGOUT_SUCCEED = 'Tracki/App/LOGOUT_SUCCEED';
export const SHOW_LOADING = 'Tracki/App/SHOW_LOADING';
export const HIDE_LOADING = 'Tracki/App/HIDE_LOADING';
export const SEARCH_TRACKERS_REQUESTED =
  'TrackiMobile/App/SEARCH_TRACKERS_REQUESTED';
export const SEARCH_TRACKERS_SUCCEED =
  'TrackiMobile/App/SEARCH_TRACKERS_SUCCEED';
export const SEARCH_TRACKERS_FAILED = 'TrackiMobile/App/SEARCH_TRACKERS_FAILED';
export const SELECTED_TRACKER = 'Tracki/App/SELECTED_TRACKER';
export const RESET_SELECTED_TRACKER = 'Tracki/App/RESET_SELECTED_TRACKER';
