/*
 *
 * MQTT constants
 *
 */

export const MQTT_START = 'Tracki/MQTT_START';
export const MQTT_CONNECTED = 'Tracki/MQTT_CONNECTED';
export const MQTT_DISCONNECT = 'Tracki/MQTT_DISCONNECT';
export const MQTT_PUBLISH = 'Tracki/MQTT_PUBLISH';
export const MQTT_TRACKER_UPDATE = 'Tracki/MQTT_TRACKER_UPDATE';
export const MQTT_TRACKERS_SUBSCRIBE_TOPIC =
  'Tracki/MQTT_TRACKERS_SUBSCRIBE_TOPIC';
export const MQTT_TRACKERS_UN_SUBSCRIBE_TOPIC =
  'Tracki/MQTT_TRACKERS_UN_SUBSCRIBE_TOPIC';
