export const FETCH_DATA_COUPONS_REQUESTED =
  'Tracki/FETCH_DATA_COUPONS_REQUESTED';
export const FETCH_DATA_COUPONS_SUCCEED = 'Tracki/FETCH_DATA_COUPONS_SUCCEED';
export const FETCH_DATA_COUPONS_FAILED = 'Tracki/FETCH_DATA_COUPONS_FAILED';
