export const FETCH_DATA_PRODUCTS_REQUESTED =
  'Tracki/FETCH_DATA_PRODUCTS_REQUESTED';
export const FETCH_DATA_PRODUCTS_SUCCEED = 'Tracki/FETCH_DATA_PRODUCTS_SUCCEED';
export const FETCH_DATA_PRODUCTS_FAILED = 'Tracki/FETCH_DATA_PRODUCTS_FAILED';
