export const FORGOT_PASSWORD_REQUESTED = 'Tracki/App/FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCEED = 'Tracki/App/FORGOT_PASSWORD_SUCCEED';
export const FORGOT_PASSWORD_FAILED = 'Tracki/App/FORGOT_PASSWORD_FAILED';
