export const FORGOT_PASSWORD_REQUESTED =
  'Tracki/Auth/FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCEED = 'Tracki/Auth/FORGOT_PASSWORD_SUCCEED';
export const FORGOT_PASSWORD_FAILED = 'Tracki/Auth/FORGOT_PASSWORD_FAILED';
export const CONFIRM_CODE_REQUESTED = 'Tracki/Auth/CONFIRM_CODE_REQUESTED';
export const CONFIRM_CODE_SUCCEED = 'Tracki/Auth/CONFIRM_CODE_SUCCEED';
export const CONFIRM_CODE_FAILED = 'Tracki/Auth/CONFIRM_CODE_FAILED';
export const RESET_AUTH_ERRORS = 'Tracki/Auth/RESET_AUTH_ERRORS';
export const RESET_ERROR_MESSAGE = 'Tracki/RESET_ERROR_MESSAGE';
export const RESET_PASSWORD_REQUESTED = 'Tracki/Auth/RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_SUCCEED = 'Tracki/Auth/RESET_PASSWORD_SUCCEED';
export const RESET_PASSWORD_FAILED = 'Tracki/Auth/RESET_PASSWORD_FAILED';
export const RESET_STORE = 'Tracki/Auth/RESET_STORE';
