export const GET_MY_WALLET_REQUESTED = 'Tracki/GET_MY_WALLET_REQUESTED';
export const GET_MY_WALLET_SUCCEED = 'Tracki/GET_MY_WALLET_SUCCEED';
export const GET_MY_WALLET_FAILED = 'Tracki/GET_MY_WALLET_FAILED';

export const GET_ADVERTIMENT_REQUESTED = 'Tracki/GET_ADVERTIMENT_REQUESTED';
export const GET_ADVERTIMENT_SUCCEED = 'Tracki/GET_ADVERTIMENT_SUCCEED';
export const GET_ADVERTIMENT_FAILED = 'Tracki/GET_ADVERTIMENT_FAILED';

export const GET_POINT_HISTORY_REQUESTED = 'Tracki/GET_POINT_HISTORY_REQUESTED';
export const GET_POINT_HISTORY_SUCCEED = 'Tracki/GET_POINT_HISTORY_SUCCEED';
export const GET_POINT_HISTORY_FAILED = 'Tracki/GET_POINT_HISTORY_FAILED';
