export const GET_MY_WALLET_REQUESTED = 'Tracki/GET_MY_WALLET_REQUESTED';
export const GET_MY_WALLET_SUCCEED = 'Tracki/GET_MY_WALLET_SUCCEED';
export const GET_MY_WALLET_FAILED = 'Tracki/GET_MY_WALLET_FAILED';

export const GET_ADVERTIMENT_REQUESTED = 'Tracki/GET_ADVERTIMENT_REQUESTED';
export const GET_ADVERTIMENT_SUCCEED = 'Tracki/GET_ADVERTIMENT_SUCCEED';
export const GET_ADVERTIMENT_FAILED = 'Tracki/GET_ADVERTIMENT_FAILED';

export const GET_POINT_HISTORY_REQUESTED = 'Tracki/GET_POINT_HISTORY_REQUESTED';
export const GET_POINT_HISTORY_SUCCEED = 'Tracki/GET_POINT_HISTORY_SUCCEED';
export const GET_POINT_HISTORY_FAILED = 'Tracki/GET_POINT_HISTORY_FAILED';

export const GET_PRODUCT_REQUESTED = 'Tracki/GET_PRODUCT_REQUESTED';
export const GET_PRODUCT_SUCCEED = 'Tracki/GET_PRODUCT_SUCCEED';
export const GET_PRODUCT_FAILED = 'Tracki/GET_PRODUCT_FAILED';

export const GET_SUBSCRIPTION_REQUESTED = 'Tracki/GET_SUBSCRIPTION_REQUESTED';
export const GET_SUBSCRIPTION_SUCCEED = 'Tracki/GET_SUBSCRIPTION_SUCCEED';
export const GET_SUBSCRIPTION_FAILED = 'Tracki/GET_SUBSCRIPTION_FAILED';

export const GET_SMS_PLAN_REQUESTED = 'Tracki/GET_SMS_PLAN_REQUESTED';
export const GET_SMS_PLAN_SUCCEED = 'Tracki/GET_SMS_PLAN_SUCCEED';
export const GET_SMS_PLAN_FAILED = 'Tracki/GET_SMS_PLAN_FAILED';

export const SET_HIDDEN_HEADDER = 'Tracki/SET_HIDDEN_HEADDER';
export const SET_VIEW_PAGE = 'Tracki/SET_VIEW_PAGE';

export const GET_TRANSACTION_DETAIL_REQUESTED =
  'Tracki/GET_TRANSACTION_DETAIL_REQUESTED';
export const GET_TRANSACTION_DETAIL_SUCCEED =
  'Tracki/GET_TRANSACTION_DETAIL_SUCCEED';
export const GET_TRANSACTION_DETAIL_FAILED =
  'Tracki/GET_TRANSACTION_DETAIL_FAILED';
