export const CHANGE_TRACKERS_TRACKING = 'Tracki/CHANGE_TRACKERS_TRACKING';

export const GET_HISTORY_TRACKER_REQUESTED =
  'Tracki/GET_HISTORY_TRACKER_REQUESTED';
export const GET_HISTORY_TRACKER_SUCCEED = 'Tracki/GET_HISTORY_TRACKER_SUCCEED';
export const GET_HISTORY_TRACKER_FAILED = 'Tracki/GET_HISTORY_TRACKER_FAILED';

export const CHANGE_TRACKING_VIEW = 'Tracki/CHANGE_TRACKING_VIEW';

export const TAB_KEYS = [
  'single_view',
  'heat_map',
  'multi_view',
  'multi_screen',
];

export const GET_ALARM_TRACKER_REQUESTED = 'Tracki/GET_ALARM_TRACKER_REQUESTED';
export const GET_ALARM_TRACKER_SUCCEED = 'Tracki/GET_ALARM_TRACKER_SUCCEED';
export const GET_ALARM_TRACKER_FAILED = 'Tracki/GET_ALARM_TRACKER_FAILED';
