export const GET_TRACKER_SETTINGS_REQUESTED =
  'Tracki/GET_TRACKER_SETTINGS_REQUESTED';
export const GET_TRACKER_SETTINGS_SUCCEED =
  'Tracki/GET_TRACKER_SETTINGS_SUCCEED';
export const GET_TRACKER_SETTINGS_FAILED = 'Tracki/GET_TRACKERS_FAILED';
