export const LOGIN_REQUESTED = 'Tracki/LOGIN_REQUESTED';
export const LOGIN_SUCCEED = 'Tracki/LOGIN_SUCCEED';
export const LOGIN_FAILED = 'Tracki/LOGIN_FAILED';
export const RESET_ERROR_MESSAGE = 'Tracki/RESET_ERROR_MESSAGE';

export const CHATUS_REQUESTED = 'Tracki/CHATUS_REQUESTED';
export const CHATUS_SUCCEED = 'Tracki/CHATUS_SUCCEED';
export const CHATUS_FAILED = 'Tracki/CHATUS_FAILED';

export const LOGIN_GEO_BOT_REQUESTED = 'Tracki/LOGIN_GEO_BOT_REQUESTED';
export const LOGIN_GEO_BOT_SUCCEED = 'Tracki/LOGIN_GEO_BOT_SUCCEED';
export const LOGIN_GEO_BOT_FAILED = 'Tracki/LOGIN_GEO_BOT_FAILED';

export const LOGIN_VIA_SOCIAL_NETWORK_REQUESTED =
  'Tracki/LOGIN_VIA_SOCIAL_NETWORK_REQUESTED';
