export const GET_RENEW_DEVICE_PLAN_REQUESTED =
  'Tracki/GET_RENEW_DEVICE_PLAN_REQUESTED';
export const GET_RENEW_DEVICE_PLAN_SUCCESSED =
  'Tracki/GET_RENEW_DEVICE_PLAN_SUCCESSED';
export const GET_RENEW_DEVICE_PLAN_FAILED =
  'Tracki/GET_RENEW_DEVICE_PLAN_FAILED';

export const BRAINTREE_DROPIN_RENEW_REQUESTED =
  'Tracki/BRAINTREE_DROPIN_RENEW_REQUESTED';
export const BRAINTREE_DROPIN_RENEW_SUCCESSED =
  'Tracki/BRAINTREE_DROPIN_RENEW_SUCCESSED';
export const BRAINTREE_DROPIN_RENEW_FAILED =
  'Tracki/BRAINTREE_DROPIN_RENEW_FAILED';

export const UPDATE_STORE = 'Tracki/UPDATE_STORE';

export const RENEW_DEVICE_REQUESTED = 'Tracki/RENEW_DEVICE_REQUESTED';
export const RENEW_DEVICE_SUCCESSED = 'Tracki/RENEW_DEVICE_SUCCESSED';
export const RENEW_DEVICE_FAILED = 'Tracki/RENEW_DEVICE_FAILED';
