export const GET_RENEW_DEVICE_PLAN_REQUESTED =
  'Tracki/GET_RENEW_DEVICE_PLAN_REQUESTED';
export const GET_RENEW_DEVICE_PLAN_SUCCESSED =
  'Tracki/GET_RENEW_DEVICE_PLAN_SUCCESSED';
export const GET_RENEW_DEVICE_PLAN_FAILED =
  'Tracki/GET_RENEW_DEVICE_PLAN_FAILED';

export const GET_TOKEN_FOR_PAYMENT_REQUESTED =
  'Tracki/GET_TOKEN_FOR_PAYMENT_REQUESTED';
export const GET_TOKEN_FOR_PAYMENT_SUCCESSED =
  'Tracki/GET_TOKEN_FOR_PAYMENT_SUCCESSED';
export const GET_TOKEN_FOR_PAYMENT_FAILED =
  'Tracki/GET_TOKEN_FOR_PAYMENT_FAILED';

export const SET_BRAINTREE_DEVICE_REQUESTED =
  'Tracki/SET_BRAINTREE_DEVICE_REQUESTED';
export const SET_BRAINTREE_DEVICE_SUCCESSED =
  'Tracki/SET_BRAINTREE_DEVICE_SUCCESSED';
export const SET_BRAINTREE_DEVICE_FAILED = 'Tracki/SET_BRAINTREE_DEVICE_FAILED';

export const BRAINTREE_DROPIN_REQUESTED = 'Tracki/BRAINTREE_DROPIN_REQUESTED';
export const BRAINTREE_DROPIN_SUCCESSED = 'Tracki/BRAINTREE_DROPIN_SUCCESSED';
export const BRAINTREE_DROPIN_FAILED = 'Tracki/BRAINTREE_DROPIN_FAILED';

export const UPDATE_STORE = 'Tracki/UPDATE_STORE';

export const RENEW_DEVICE_REQUESTED = 'Tracki/RENEW_DEVICE_REQUESTED';
export const RENEW_DEVICE_SUCCESSED = 'Tracki/RENEW_DEVICE_SUCCESSED';
export const RENEW_DEVICE_FAILED = 'Tracki/RENEW_DEVICE_FAILED';
