export const GET_CONTRY_CODE_REQUESTED = 'Tracki/GET_CONTRY_CODE_REQUESTED';
export const GET_CONTRY_CODE_SUCCESSED = 'Tracki/GET_CONTRY_CODE_SUCCESSED';
export const GET_CONTRY_CODE_FAILED = 'Tracki/GET_CONTRY_CODE_FAILED';

export const GET_CONTRY_CODE_FOLLOW_REQUESTED =
  'Tracki/GET_CONTRY_CODE_FOLLOW_REQUESTED';
export const GET_CONTRY_CODE_FOLLOW_SUCCESSED =
  'Tracki/GET_CONTRY_CODE_FOLLOW_SUCCESSED';
export const GET_CONTRY_CODE_FOLLOW_FAILED =
  'Tracki/GET_CONTRY_CODE_FOLLOW_FAILED';

export const UPDATE_SUBSCRIPTION_STORE = 'Tracki/UPDATE_SUBSCRIPTION_STORE';

export const BRAINTREE_DROPIN_SUBSCRIPTION_REQUESTED =
  'Tracki/BRAINTREE_DROPIN_SUBSCRIPTION_REQUESTED';
export const BRAINTREE_DROPIN_SUBSCRIPTION_SUCCESSED =
  'Tracki/BRAINTREE_DROPIN_SUBSCRIPTION_SUCCESSED';
export const BRAINTREE_DROPIN_SUBSCRIPTION_FAILED =
  'Tracki/BRAINTREE_DROPIN_SUBSCRIPTION_FAILED';

export const BUY_SMS_SUBSCRIPTION_REQUESTED =
  'Tracki/BUY_SMS_SUBSCRIPTION_REQUESTED';
export const BUY_SMS_SUBSCRIPTION_SUCCESSED =
  'Tracki/BUY_SMS_SUBSCRIPTION_SUCCESSED';
export const BUY_SMS_SUBSCRIPTION_FAILED = 'Tracki/BUY_SMS_SUBSCRIPTION_FAILED';

export const BUY_FAST_TRACKING_SUBSCRIPTION_REQUESTED =
  'Tracki/BUY_FAST_TRACKING_SUBSCRIPTION_REQUESTED';
export const BUY_FAST_TRACKING_SUBSCRIPTION_SUCCESSED =
  'Tracki/BUY_FAST_TRACKING_SUBSCRIPTION_SUCCESSED';
export const BUY_FAST_TRACKING_SUBSCRIPTION_FAILED =
  'Tracki/BUY_FAST_TRACKING_SUBSCRIPTION_FAILED';

export const GET_FATS_TRACKING_FOLLOW_CODE_REQUESTED =
  'Tracki/GET_FATS_TRACKING_FOLLOW_CODE_REQUESTED';
export const GET_FATS_TRACKING_FOLLOW_CODE_SUCCEED =
  'Tracki/GET_FATS_TRACKING_FOLLOW_CODE_SUCCEED';
export const GET_FATS_TRACKING_FOLLOW_CODE_FAILED =
  'Tracki/GET_FATS_TRACKING_FOLLOW_CODE_FAILED';
