export const GET_HISTORY_TRACKER_REQUESTED =
  'Tracki/GET_HISTORY_TRACKER_REQUESTED';
export const GET_HISTORY_TRACKER_SUCCEED = 'Tracki/GET_HISTORY_TRACKER_SUCCEED';
export const GET_HISTORY_TRACKER_FAILED = 'Tracki/GET_HISTORY_TRACKER_FAILED';
