export const CREATE_NEW_CONTACT_REQUESTED =
  'Tracki/CREATE_NEW_CONTACT_REQUESTED';
export const CREATE_NEW_CONTACT_SUCCESSED =
  'Tracki/CREATE_NEW_CONTACT_SUCCESSED';
export const CREATE_NEW_CONTACT_FAILED = 'Tracki/CREATE_NEW_CONTACT_FAILED';
