export const TAB_KEYS = ['overview', 'history', 'stop', 'trip', 'speed'];

export const FETCH_NOTIFICATION_UNREAD_REQUESTED =
  'Tracki/FETCH_NOTIFICATION_UNREAD_REQUESTED';
export const FETCH_NOTIFICATION_UNREAD_SUCCEED =
  'Tracki/FETCH_NOTIFICATION_UNREAD_SUCCEED';
export const FETCH_NOTIFICATION_UNREAD_FAILED =
  'Tracki/FETCH_NOTIFICATION_UNREAD_FAILED';

export const FETCH_HISTORY_RECENT_STOP_REQUESTED =
  'Tracki/FETCH_HISTORY_RECENT_STOP_REQUESTED';
export const FETCH_HISTORY_RECENT_STOP_SUCCEED =
  'Tracki/FETCH_HISTORY_RECENT_STOP_SUCCEED';
export const FETCH_HISTORY_RECENT_STOP_FAILED =
  'Tracki/FETCH_HISTORY_RECENT_STOP_FAILED';

export const CHANGE_REPORT_VIEW_MODE = 'Tracki/CHANGE_REPORT_VIEW_MODE';
